const triviaFacts=[
{text:'Venus takes about 243 Earth days to spin once, but only about 225 days to orbit the Sun. Its rotation takes longer than its year.',source:'https://science.nasa.gov/venus/venus-facts/'},
{text:'An octopus has three hearts: two send blood to its gills, and the third sends it around the rest of its body.',source:'https://oceanservice.noaa.gov/news/feb26/undersea-creatures-valentines-day.html'},
{text:'Flamingos get their pink color from pigments in the food they eat, including algae and shrimp.',source:'https://nationalzoo.si.edu/animals/american-flamingo'},
{text:'The Statue of Liberty’s copper skin is only about 2.5 millimeters thick—roughly the thickness of two American pennies stacked together.',source:'https://www.nps.gov/stli/faqs.htm'},
{text:'The Statue of Liberty was originally copper-brown, like a penny. Its familiar green color developed over time.',source:'https://www.nps.gov/stli/faqs.htm'},
{text:'In 1815, Congress bought Thomas Jefferson’s personal library of 6,487 books to help replace its collection after the Capitol fire.',source:'https://loc.gov/exhibits/thomas-jeffersons-library/overview.html'},
{text:'Wombats produce cube-shaped droppings. Researchers linked the unusual shape to the way their intestines work.',source:'https://apnews.com/article/d97862f5a9b86dbacc1293e2a8adc9f9'}
];
window.renderExtras=function(){const current=new Date(),d=iso(current),day=Math.floor(Date.UTC(current.getFullYear(),current.getMonth(),current.getDate())/86400000);let order=triviaFacts.map((_,i)=>i),random=rng(7319);for(let i=order.length-1;i>0;i--){let j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}const fact=triviaFacts[order[((day%order.length)+order.length)%order.length]];if(triviaLoaded!==d){showOfflineFact();}loadDailyTrivia();const start=new Date(selected),end=new Date(selected);end.setDate(end.getDate()+6);$('#upcomingrange').textContent=fmt(start,{month:'short',day:'numeric'})+' – '+fmt(end,{month:'short',day:'numeric'});$('#upcoming').replaceChildren();let count=0;for(let i=0;i<7;i++){const date=new Date(start);date.setDate(date.getDate()+i);for(const task of list(iso(date)).filter(t=>!data.done[t.id+'_'+iso(date)])){count++;const b=el('button','upcoming-task',task.title);const when=iso(date)===today()?'Today':fmt(date,{weekday:'short',month:'short',day:'numeric'});b.append(el('small','',when+(task.time?' · '+new Date('2000-01-01T'+task.time).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'')));b.onclick=()=>{selected=new Date(date);cal=new Date(date);render();$('.note').scrollIntoView({behavior:'smooth',block:'start'})};$('#upcoming').append(b)}}if(!count)$('#upcoming').append(el('p','','No upcoming tasks this week.'))};
let lastLottery=null,loadingLottery=false;function lotteryGameCard(game){const card=el('section','lottery-game'),heading=el('h3','',game.name),date=el('p','draw-date',new Date(game.drawDate).toLocaleDateString('en-US',{timeZone:'America/Detroit',month:'short',day:'numeric',year:'numeric'})),balls=el('div','lottery-balls');balls.setAttribute('aria-label','Winning numbers: '+game.numbers.join(', '));for(const number of game.numbers){const ball=el('span','lottery-ball',String(number));ball.setAttribute('aria-hidden','true');balls.append(ball)}if(game.special){const special=el('p','special-number',game.special);card.append(heading,date,balls,special)}else card.append(heading,date,balls);return card}function validLottery(result){return result&&Number.isFinite(Date.parse(result.checkedAt))&&Array.isArray(result.games)&&result.games.length>0&&result.games.every(g=>typeof g.name==='string'&&Number.isFinite(Date.parse(g.drawDate))&&Array.isArray(g.numbers)&&g.numbers.length>0&&g.numbers.every(n=>Number.isInteger(n)&&n>=0&&n<=99))}
function drawLottery(result){$('#lotteryresults').replaceChildren();const grid=el('div','lottery-game-grid');for(const game of result.games.slice(0,4))grid.append(lotteryGameCard(game));$('#lotteryresults').append(grid);if(result.games.length>4){const details=el('details','lottery-more'),summary=el('summary','','More lottery results');details.append(summary);const more=el('div','lottery-game-grid');for(const game of result.games.slice(4))more.append(lotteryGameCard(game));details.append(more);$('#lotteryresults').append(details)}$('#lotterystatus').textContent='Checked '+new Date(result.checkedAt).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+'. Source: Michigan Lottery.'+(Date.now()-Date.parse(result.checkedAt)>3*60*60*1000?' Results need an update; check the draw dates.':'')}
async function refreshLottery(){if(loadingLottery)return;loadingLottery=true;$('#refreshlottery').disabled=true;$('#lotterystatus').textContent='Checking Michigan Lottery…';try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let result;try{const response=await fetch('lottery.json?t='+Date.now(),{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error();result=await response.json()}finally{clearTimeout(timer)}if(!validLottery(result))throw Error();lastLottery=result;drawLottery(result);try{localStorage.setItem('dad-lottery',JSON.stringify(result))}catch{}}catch{if(lastLottery){drawLottery(lastLottery);$('#lotterystatus').textContent+=' Could not refresh. These are previously saved results; check the draw dates.'}else{$('#lotteryresults').textContent='Results are temporarily unavailable.';$('#lotterystatus').textContent='Tap the Michigan Lottery link for the latest numbers.'}}finally{loadingLottery=false;$('#refreshlottery').disabled=false}}
$('#refreshlottery').onclick=refreshLottery;try{lastLottery=JSON.parse(localStorage.getItem('dad-lottery'));if(validLottery(lastLottery))drawLottery(lastLottery);else lastLottery=null}catch{}refreshLottery();let observedDay=today();setInterval(()=>{if(document.visibilityState==='visible'){const now=today();if(now!==observedDay){if(iso(selected)===observedDay){selected=new Date();cal=new Date()}observedDay=now;render()}refreshLottery()}},15*60*1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){const now=today();if(now!==observedDay){if(iso(selected)===observedDay){selected=new Date();cal=new Date()}observedDay=now;render()}refreshLottery()}});

document.querySelectorAll("[data-footer-page]").forEach(link=>link.onclick=e=>{e.preventDefault();document.querySelector(`[data-page="${link.dataset.footerPage}"]`).click();window.scrollTo({top:0,behavior:"smooth"})});

let triviaRequest='',triviaLoaded='',triviaOffset=0,triviaEvents=[],offlineDate='',offlineOffset=0;
function localDayNumber(){const n=new Date();return Math.floor(Date.UTC(n.getFullYear(),n.getMonth(),n.getDate())/86400000)}
function validTrivia(f){try{return typeof f?.text==='string'&&f.text.length>0&&Number.isInteger(f.year)&&new URL(f.source).protocol==='https:'&&new URL(f.source).hostname==='en.wikipedia.org'}catch{return false}}
function showOfflineFact(){if(offlineDate!==today()){offlineDate=today();offlineOffset=0;}const f=triviaFacts[(localDayNumber()+offlineOffset)%triviaFacts.length];$('#trivia').textContent=f.text;$('#triviasource').href=f.source;$('#triviasource').textContent='Read more';}
const triviaStatus=el('p','small');triviaStatus.setAttribute('role','status');$('#triviasource').after(triviaStatus);
const moreTrivia=el('button','','Another fact');$('#triviasource').after(moreTrivia);
function showOnlineFact(){if(!triviaEvents.length)return;const f=triviaEvents[((triviaOffset%triviaEvents.length)+triviaEvents.length)%triviaEvents.length];$('#trivia').textContent=f.year+' — '+f.text;$('#triviasource').href=f.source;$('#triviasource').textContent='Wikipedia · CC BY-SA · Read more';}
async function loadDailyTrivia(){const date=today();if(triviaLoaded===date){showOnlineFact();return}if(triviaRequest===date)return;triviaRequest=date;triviaStatus.textContent='Checking today’s facts…';
try{let cached;try{cached=JSON.parse(localStorage.getItem('tom-trivia-online'))}catch{}
if(cached?.date===date&&Array.isArray(cached.events)&&cached.events.length&&cached.events.every(validTrivia)){triviaEvents=cached.events;triviaStatus.textContent='Today’s saved online edition · '+date;}
else{const now=new Date(),mm=String(now.getMonth()+1).padStart(2,'0'),dd=String(now.getDate()).padStart(2,'0'),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);
let result;try{const response=await fetch('https://en.wikipedia.org/api/rest_v1/feed/onthisday/events/'+mm+'/'+dd,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error();result=await response.json()}finally{clearTimeout(timer)}
const events=(Array.isArray(result.events)?result.events:[]).filter(f=>typeof f.text==='string'&&Number.isInteger(f.year)&&f.pages?.some(p=>p.content_urls?.desktop?.page)).map(f=>({text:f.text,year:f.year,source:f.pages.find(p=>p.content_urls?.desktop?.page).content_urls.desktop.page})).filter(validTrivia);
if(!events.length)throw Error();if(today()!==date)return;triviaEvents=events;try{localStorage.setItem('tom-trivia-online',JSON.stringify({date,events}))}catch{}triviaStatus.textContent='Online daily edition · '+date;}
triviaLoaded=date;triviaOffset=localDayNumber()%triviaEvents.length;showOnlineFact();
}catch{if(today()!==date)return;showOfflineFact();triviaStatus.textContent='Offline daily fact · '+date+' · Online facts will retry when connected.'}
finally{if(triviaRequest===date)triviaRequest=''}}
moreTrivia.onclick=()=>{if(triviaLoaded===today()&&triviaEvents.length){triviaOffset++;showOnlineFact()}else{offlineOffset++;showOfflineFact();loadDailyTrivia()}};
window.addEventListener('online',loadDailyTrivia);
setInterval(()=>{if(document.visibilityState==='visible'){const now=today();if(now!==observedDay){if(iso(selected)===observedDay){selected=new Date();cal=new Date()}observedDay=now;render()}else renderExtras()}},60000);
renderExtras();
