const triviaFacts=[
{text:'Venus takes about 243 Earth days to spin once, but only about 225 days to orbit the Sun. Its rotation takes longer than its year.',source:'https://science.nasa.gov/venus/venus-facts/'},
{text:'An octopus has three hearts: two send blood to its gills, and the third sends it around the rest of its body.',source:'https://oceanservice.noaa.gov/news/feb26/undersea-creatures-valentines-day.html'},
{text:'Flamingos get their pink color from pigments in the food they eat, including algae and shrimp.',source:'https://nationalzoo.si.edu/animals/american-flamingo'},
{text:'The Statue of Liberty’s copper skin is only about 2.5 millimeters thick—roughly the thickness of two American pennies stacked together.',source:'https://www.nps.gov/stli/faqs.htm'},
{text:'The Statue of Liberty was originally copper-brown, like a penny. Its familiar green color developed over time.',source:'https://www.nps.gov/stli/faqs.htm'},
{text:'In 1815, Congress bought Thomas Jefferson’s personal library of 6,487 books to help replace its collection after the Capitol fire.',source:'https://loc.gov/exhibits/thomas-jeffersons-library/overview.html'},
{text:'Wombats produce cube-shaped droppings. Researchers linked the unusual shape to the way their intestines work.',source:'https://apnews.com/article/d97862f5a9b86dbacc1293e2a8adc9f9'}
];
window.renderExtras=function(){const d=iso(selected),day=Math.floor(Date.UTC(selected.getFullYear(),selected.getMonth(),selected.getDate())/86400000);let order=triviaFacts.map((_,i)=>i),random=rng(7319);for(let i=order.length-1;i>0;i--){let j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}const fact=triviaFacts[order[((day%order.length)+order.length)%order.length]];$('#trivia').textContent=fact.text;$('#triviasource').href=fact.source;const start=new Date(selected),end=new Date(selected);end.setDate(end.getDate()+6);$('#upcomingrange').textContent=fmt(start,{month:'short',day:'numeric'})+' – '+fmt(end,{month:'short',day:'numeric'});$('#upcoming').replaceChildren();let count=0;for(let i=0;i<7;i++){const date=new Date(start);date.setDate(date.getDate()+i);for(const task of list(iso(date)).filter(t=>!data.done[t.id+'_'+iso(date)])){count++;const b=el('button','upcoming-task',task.title);const when=iso(date)===today()?'Today':fmt(date,{weekday:'short',month:'short',day:'numeric'});b.append(el('small','',when+(task.time?' · '+new Date('2000-01-01T'+task.time).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'')));b.onclick=()=>{selected=new Date(date);cal=new Date(date);render();$('.note').scrollIntoView({behavior:'smooth',block:'start'})};$('#upcoming').append(b)}}if(!count)$('#upcoming').append(el('p','','No upcoming tasks this week.'))};
let lastLottery=null,loadingLottery=false;function lotteryGameCard(game){const card=el('section','lottery-game'),heading=el('h3','',game.name),date=el('p','draw-date',new Date(game.drawDate).toLocaleDateString('en-US',{timeZone:'America/Detroit',month:'short',day:'numeric',year:'numeric'})),balls=el('div','lottery-balls');balls.setAttribute('aria-label','Winning numbers: '+game.numbers.join(', '));for(const number of game.numbers){const ball=el('span','lottery-ball',String(number));ball.setAttribute('aria-hidden','true');balls.append(ball)}if(game.special){const special=el('p','special-number',game.special);card.append(heading,date,balls,special)}else card.append(heading,date,balls);return card}function drawLottery(result){$('#lotteryresults').replaceChildren();const grid=el('div','lottery-game-grid');for(const game of result.games.slice(0,4))grid.append(lotteryGameCard(game));$('#lotteryresults').append(grid);if(result.games.length>4){const details=el('details','lottery-more'),summary=el('summary','','More lottery results');details.append(summary);const more=el('div','lottery-game-grid');for(const game of result.games.slice(4))more.append(lotteryGameCard(game));details.append(more);$('#lotteryresults').append(details)}$('#lotterystatus').textContent='Checked '+new Date(result.checkedAt).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+'. Source: Michigan Lottery.'+(Date.now()-Date.parse(result.checkedAt)>3*60*60*1000?' Results need an update; check the draw dates.':'')}
async function refreshLottery(){if(loadingLottery)return;loadingLottery=true;$('#refreshlottery').disabled=true;$('#lotterystatus').textContent='Checking Michigan Lottery…';try{const response=await fetch('https://raw.githubusercontent.com/bearicide/bearicide.github.io/main/tom/lottery.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error();const result=await response.json();if(!Array.isArray(result.games)||!result.games.length)throw Error();lastLottery=result;drawLottery(result);try{localStorage.setItem('dad-lottery',JSON.stringify(result))}catch{}}catch{if(lastLottery){drawLottery(lastLottery);$('#lotterystatus').textContent+=' Could not refresh. These are previously saved results; check the draw dates.'}else{$('#lotteryresults').textContent='Results are temporarily unavailable.';$('#lotterystatus').textContent='Tap the Michigan Lottery link for the latest numbers.'}}finally{loadingLottery=false;$('#refreshlottery').disabled=false}}
$('#refreshlottery').onclick=refreshLottery;try{lastLottery=JSON.parse(localStorage.getItem('dad-lottery'));if(lastLottery)drawLottery(lastLottery)}catch{}renderExtras();refreshLottery();let observedDay=today();setInterval(()=>{if(document.visibilityState==='visible'){const now=today();if(now!==observedDay){if(iso(selected)===observedDay){selected=new Date();cal=new Date()}observedDay=now;render()}refreshLottery()}},15*60*1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){const now=today();if(now!==observedDay){if(iso(selected)===observedDay){selected=new Date();cal=new Date()}observedDay=now;render()}refreshLottery()}});

document.querySelectorAll("[data-footer-page]").forEach(link=>link.onclick=e=>{e.preventDefault();document.querySelector(`[data-page="${link.dataset.footerPage}"]`).click();window.scrollTo({top:0,behavior:"smooth"})});
